spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: root
    password: mocha127
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

password: password

main:
  title: mocha's blog
  description: 대한민국 청소년 개발자 hwangseonu의 블로그입니다.